stages:
  check:
    cmd: python3 src/check.py
    deps:
      - src/check.py
    outs:
      - workingdir/powerpoint.pptx

  convert_pptx_to_pdf:
    cmd: python3 src/pptx2pdf.py
    deps:
      - src/pptx2pdf.py
      - workingdir/powerpoint.pptx
    outs:
      - assets/powerpoint.pdf

  convert_pdf_to_images:
    cmd: python3 src/pdf2png.py assets/powerpoint.pdf
    deps:
      - src/pdf2png.py
      - assets/powerpoint.pdf
    outs:
      - assets/images/

  extract_notes_from_powerpoint:
    cmd: python3 src/extract_notes.py
    deps:
      - workingdir/powerpoint.pptx
      - src/extract_notes.py
    outs:
      - assets/notes/

  create_silent_video:
    cmd: ./src/create_silent_audio.sh 0.5 assets silence.mp3
    deps:
      - src/create_silent_audio.sh
    outs:
      - assets/silence.mp3

  text_to_speech:
    cmd: python3 src/text2speech.py
    deps:
      - src/text2speech.py
      - assets/silence.mp3
      - assets/notes/
    outs:
      - assets/voiceovers/

  generate_videoclips:
    cmd: python3 src/generate_videoclips.py assets
    deps:
      - src/generate_videoclips.py
      - assets/images/
      - assets/voiceovers/
    outs:
      - assets/videoclips/

  assemble_video:
    cmd: python3 src/assemble_video.py assets
    deps:
      - src/assemble_video.py
      - assets/videoclips/
    outs:
      - output/
